# Generated by Django 4.2.4 on 2024-03-21 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', models.CharField(blank=True, max_length=250, null=True, unique=True)),
                ('ipv4_address', models.CharField(blank=True, max_length=250, null=True)),
                ('last_seen', models.DateTimeField()),
                ('confidence_factor', models.FloatField()),
                ('x_pos', models.CharField()),
                ('y_pos', models.CharField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
