# Generated by Django 4.2.4 on 2024-03-21 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicelocation',
            name='last_seen',
        ),
    ]
